sudo: required
services:
  - docker

before_install: 
  - docker build -t nmxmxh/docker-react -f Dockerfile.dev .  

script:
  - docker run nmxmxh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "name-in-all-applications"
  env: "name-of-environment"
  bucket_name: "name-of-bucket-for-zip"
  bucket_path: "name-of-folder-with-name-of-project (app name)"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secret: "$AWS_SECRET_KEY"


# IAM for managing api keys
# policies ? permissions for new user.
# you can search through description.
# secret access key is shown only once.
# do not put keys directly in repo.
# environment secrets provided by Travis CI.
# environment variables in Travis.
# AWS_SECRET_KEY | AWS_ACCESS_KEY