apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    component: web
spec:
  containers:
    - name: myapp
      image: nmxmxh/multi-docker
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
